yaronzz/Tidal-Media-Downloader

TIDALDL-PY/tidal_dl/__init__.py
TIDALDL-PY/tidal_dl/__main__.py
TIDALDL-PY/tidal_dl/check.py
TIDALDL-PY/tidal_dl/download.py
TIDALDL-PY/tidal_dl/tidal.py

Most of the changes are really just code formatted properly. The main change is the fix of the partial downloaded album check.

fixed some bugs and polished some code

---

README.md
TIDALDL-PY/requirements.txt

Also not sure what to do about futures, also couldn't install that at the requested version

syntax fix (pip would not install with current)

---

TIDALDL-UI/TIDALDL-UI/Tidal/TidalTool.cs

Fixes a crash to desktop if no album cover image exists.
This bug was reported in the Telegram group.

Changed cover image retieval to fallback to artist image if no album cover exists.

---

TIDALDL-PY/tidal_dl/download.py
TIDALDL-PY/tidal_dl/tidal.py

Added in the functionality to pass URLs for playlists through downloadURL. 
Thanks for making this!

Made Playlists available to downloadURL

---

TIDALDL-PY/tidal_dl/__init__.py
TIDALDL-PY/tidal_dl/download.py
TIDALDL-PY/tidal_dl/tidal.py

Add Year before album title:
[2019] Album title

Add Year before album title

---

TIDALDL-PY/tidal_dl/download.py

Not sure what else to say tbh, any questions?

Added Clean/Explicit to the file name depending on Tidal's metadata

---

TIDALDL-PY/tidal_dl/__init__.py
TIDALDL-PY/tidal_dl/download.py
TIDALDL-PY/tidal_dl/tidal.py

Example of the 3 choices for an album title :

Add choice to tag the year before or after album title

---

TIDALDL-PY/tidal_dl/lang/vietnamese.py

added Vietnamese language
Do you think that could be merged?
Should I do something more?

add vietnamese.py

---

TIDALDL-PY/tidal_dl/download.py

Removes the 'E' from the album folder name if addExplicitFlag is False.

Album flag respects the addExplicitTag setting

---

TIDALDL-PY/tidal_dl/download.py

This MR makes possible to download multiple URLs at a time when inside tidal-dl. Simply, paste the URLs separated by a space and it will recursively download each link.

Ability to download multiple urls at a time.

---

TIDALDL-PY/tidal_dl/lang/danish.py
TIDALDL-PY/tidal_dl/lang/language.py

I have attempted to translate most of it to Danish. 
As far as I can see the changes I made should be enough to include the danish language.

Add Danish translation

---

TIDALDL-PY/tidal_dl/download.py

```__file__``` supposed to be variable from Python

Replace __file__ to file

---

TIDALDL-PY/tidal_dl/lang/english.py

Fix typo in the english language, issue #655

Fix typo in "quality" word

---

TIDALDL-PY/tidal_dl/download.py

Should also address the metadata part of #295.

Include version in track metadata

---

TIDALDL-PY/tidal_dl/lang/hungarian.py
TIDALDL-PY/tidal_dl/lang/language.py

Add Hungarian language and closes  #629

New language Hungarian

---

TIDALDL-PY/tidal_dl/__init__.py
TIDALDL-PY/tidal_dl/download.py
TIDALDL-PY/tidal_dl/lang/arabic.py
TIDALDL-PY/tidal_dl/lang/chinese.py
TIDALDL-PY/tidal_dl/lang/croatian.py
TIDALDL-PY/tidal_dl/lang/czech.py
TIDALDL-PY/tidal_dl/lang/danish.py
TIDALDL-PY/tidal_dl/lang/english.py
TIDALDL-PY/tidal_dl/lang/filipino.py
TIDALDL-PY/tidal_dl/lang/french.py
TIDALDL-PY/tidal_dl/lang/german.py
TIDALDL-PY/tidal_dl/lang/hungarian.py
TIDALDL-PY/tidal_dl/lang/italian.py
TIDALDL-PY/tidal_dl/lang/portuguese.py
TIDALDL-PY/tidal_dl/lang/russian.py
TIDALDL-PY/tidal_dl/lang/spanish.py
TIDALDL-PY/tidal_dl/lang/turkish.py
TIDALDL-PY/tidal_dl/lang/ukrainian.py
TIDALDL-PY/tidal_dl/lang/vietnamese.py
TIDALDL-PY/tidal_dl/printf.py
TIDALDL-PY/tidal_dl/settings.py

I added support for timed lyrics - .lrc files. 
if timed lyrics exist:
1. Timed lyrics will be downloaded into the same directory as the song. The file name will match the file name of the song
2. Timed Lyrics file will have the exact same file name as the song, with the exception of the file extension. The extension will be .lrc

Timed lyrics - .lrc files

---

TIDALDL-PY/tidal_dl/lang/english.py
TIDALDL-PY/tidal_dl/lang/korean.py

While using the program, I found that there was some incorrect translations and corrected it.

update english.py & korean.py

---

TIDALDL-PY/tidal_dl/__init__.py

After setting access token I was getting error that country code is missing. This helped fix the issue for me.

Fix set access token typo and countryCode

---

TIDALDL-PY/tidal_dl/lang/arabic.py
TIDALDL-PY/tidal_dl/lang/chinese.py
TIDALDL-PY/tidal_dl/lang/croatian.py
TIDALDL-PY/tidal_dl/lang/czech.py
TIDALDL-PY/tidal_dl/lang/danish.py
TIDALDL-PY/tidal_dl/lang/dutch.py
TIDALDL-PY/tidal_dl/lang/english.py
TIDALDL-PY/tidal_dl/lang/filipino.py
TIDALDL-PY/tidal_dl/lang/french.py
TIDALDL-PY/tidal_dl/lang/german.py
TIDALDL-PY/tidal_dl/lang/hungarian.py
TIDALDL-PY/tidal_dl/lang/italian.py
TIDALDL-PY/tidal_dl/lang/japanese.py
TIDALDL-PY/tidal_dl/lang/korean.py
TIDALDL-PY/tidal_dl/lang/language.py
TIDALDL-PY/tidal_dl/lang/polish.py
TIDALDL-PY/tidal_dl/lang/portuguese.py
TIDALDL-PY/tidal_dl/lang/russian.py
TIDALDL-PY/tidal_dl/lang/spanish.py
TIDALDL-PY/tidal_dl/lang/turkish.py
TIDALDL-PY/tidal_dl/lang/ukrainian.py
TIDALDL-PY/tidal_dl/lang/vietnamese.py
TIDALDL-PY/tidal_dl/printf.py
TIDALDL-PY/tidal_dl/util.py

Add Polish translation, global typo fixes

---

.github/workflows/stale.yml

@yaronzz I've increased the number of operations for the stale job.

Update stale job increase number of operations

---

TIDALDL-PY/tidal_dl/tidal.py

header set to {} then immediately given new value

Removed unused assignment

---

TIDALDL-PY/tidal_dl/gui.py

Hi. 
This is a proposal to perform an Artist search and to download every artist album. 
If you see any reason why we should not perform this (API Limitation, being flagged and have our token revoked) please tell me. 
If this is OK I would like to go further and also add the capability to have favorites artists to automatically look and download new releases when we open the app.

Add capability to perform an artist search and download all albums

---

TIDALDL-PY/tidal_dl/lang/hungarian.py

@yaronzz as requested in #966 I've updated the Hungarian language, thanks @szikib82

Update Hungarian language

---

TIDALDL-PY/tidal_dl/tidal.py

Hi,
for #986 I check and I found I get 429 http error code witch is for Too Many reqeust I have implemented a fix but I don't have time to but it in a setting.
For the #970 I add a check to see if the track is streambable, if not we can't play it through tidal or this app
Thanks for the tool!

Fix issue #970 and #986

---

TIDALDL-PY/requirements.txt
TIDALDL-PY/tidal_dl/__init__.py
TIDALDL-PY/tidal_dl/download.py
TIDALDL-PY/tidal_dl/events.py
TIDALDL-PY/tidal_dl/gui.py
TIDALDL-PY/tidal_dl/lang/language.py
TIDALDL-PY/tidal_dl/paths.py
TIDALDL-PY/tidal_dl/printf.py
TIDALDL-PY/tidal_dl/settings.py
TIDALDL-PY/tidal_dl/tidal.py

I have basically created a view on the left side of the GUI, that shows the user's playlists. You can click on them and the tracks will be displayed in the search result table. 
It is now possible to select several tracks and click on download, to download them without the need to click "Download" for every single track.
According to your coding style, you are likely a C# engineer. I tried to create a more Pythonic code, thus it differs from your style a little bit. Your code is a little bit hacky and not very Pythonic. Extending it makes it hard but it works stable this way. There is a lot of refactoring potential.
But anyway, I would be glad, if you could merge this pull request and push it to PyPi.

[GUI] Show user's playlists and allow to download them.
